### ISSUE TITLE
Does this only support GRUB?

### ISSUE THREAD

**Issue by orhun** [masksshow/Thinkpad-E14-15-AMD-Gen-2-FIX#11]
I'm not familiar with the technical details but is it possible to port the script somehow and apply this fix on an Arch Linux system which uses `systemd-boot`?

**Comment by masksshow** [comment]
https://github.com/masksshow/Thinkpad-E14-15-AMD-Gen-2-FIX/blob/main/thinkpad-e15-gen2-firmware-fix_arch.sh
Better to ask the person who added this script.

**Comment by shalzz** [comment]
This works with systemd-boot as well but you'll have to manually setup the config following the instructions here:
https://wiki.archlinux.org/title/DSDT#Using_a_CPIO_archive
Look at the script for grub on how to create the dsl file. You'll also have to most likely update the OEM version in the dsl file which is also explained in the arch wiki.

**Comment by masksshow** [comment]
> This works with systemd-boot as well but you'll have to manually setup the config following the instructions here: https://wiki.archlinux.org/title/DSDT#Using_a_CPIO_archive Look at the script for grub on how to create the dsl file. You'll also have to most likely update the OEM version in the dsl file which is also explained in the arch wiki.

Yes. Fine!
