### ISSUE TITLE
Script not working on fresh installed Ubuntu 20.04 (Windows UEFI dual boot)

### ISSUE THREAD

**Issue by alvaro-gh** [masksshow/Thinkpad-E14-15-AMD-Gen-2-FIX#12]
Hey, I found out about the fn keys issue as everyone else and ended up here. I downloaded the script, replaced both occurrences of `/bin/sh`, and ran with `sudo ./fix.sh --grub-setup-dsdt`, I even tried the sed command but nothing happened. I'd like to help but I have no idea how to troubleshoot this.
Some data about this installation:
```
Linux <redacted> 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

BIOS Information
        Vendor: LENOVO
        Version: R1AET37W (1.13 )
        Release Date: 04/09/2021
```

Is it because I'm not using kernels 5.8 or 5.9?
Thanks for your time.

**Comment by masksshow** [comment]
Hi. This is very strange. Usually on Ubuntu there is no problem.
Have you tried reading what the console output is, maybe there are errors there.
I have Ubuntu, I tested only on 5.8 and 5.9

**Comment by alvaro-gh** [comment]
Closing this since not even the battery charge was working correctly. I'll wait until Lenovo decides to fix this. Thanks for replying masksshow :)
