### ISSUE TITLE
Doesn't work on Fedora 34

### ISSUE THREAD

**Issue by atisDu** [masksshow/Thinkpad-E14-15-AMD-Gen-2-FIX#8]

**Comment by ghost** [comment]
what output does it show  when you run the script ( sudo ./thinkpad-e15-gen2-firmware-fix_fedora.sh --grub-setup-dsdt ) ?  Maybe that would help .

**Comment by atisDu** [comment]
I also tried the regular one and on arch the arch one and regular, they all seem to have the same output: 
`Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20210331
Copyright (c) 2000 - 2021 Intel Corporation

File appears to be binary: found 18252 non-ASCII characters, disassembling
Binary file appears to be a valid ACPI table, disassembling
Input file dsdt.dat, Length 0xD80B (55307) bytes
ACPI: DSDT 0x0000000000000000 00D80B (v01 LENOVO TP-R1A   00001130 INTL 20180313)
Pass 1 parse of [DSDT]
Pass 2 parse of [DSDT]
Parsing Deferred Opcodes (Methods/Buffers/Packages/Regions)

Parsing completed
Disassembly completed
ASL Output:    dsdt.dsl - 472403 bytes

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20210331
Copyright (c) 2000 - 2021 Intel Corporation

dsdt.dsl    724:     Method (PMON, 2, NotSerialized)
Remark   2120 -                ^ Control Method should be made Serialized due to creation of named objects within (\PMON)

dsdt.dsl    727:         Name (TSTR, Buffer (Local0){})
Remark   2173 -                  ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\PMON)

dsdt.dsl    733:     Method (LDBG, 2, NotSerialized)
Remark   2120 -                ^ Control Method should be made Serialized due to creation of named objects within (\LDBG)

dsdt.dsl    736:         Name (TSTR, Buffer (Local0){})
Remark   2173 -                  ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\LDBG)

dsdt.dsl    841:         OperationRegion (VARM, SystemMemory, Local0, 0x01)
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\LM01)

dsdt.dsl    853:         OperationRegion (VARM, SystemMemory, Local0, 0x02)
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\LM02)

dsdt.dsl    865:         OperationRegion (VARM, SystemMemory, Local0, 0x04)
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\LM03)

dsdt.dsl    877:         OperationRegion (VARM, SystemMemory, Local0, 0x01)
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\LM04)

dsdt.dsl    889:         OperationRegion (VARM, SystemMemory, Local0, 0x02)
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\LM05)

dsdt.dsl    901:         OperationRegion (VARM, SystemMemory, Local0, 0x04)
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\LM06)

dsdt.dsl    913:         OperationRegion (VARI, SystemIO, Local0, 0x01)
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\LM07)

dsdt.dsl    925:         OperationRegion (VARJ, SystemIO, Local0, 0x02)
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\LM08)

dsdt.dsl    937:         OperationRegion (VARK, SystemIO, Local0, 0x01)
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\LM09)

dsdt.dsl    949:         OperationRegion (VARL, SystemIO, Local0, 0x02)
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\LM0A)

dsdt.dsl   1074:         OperationRegion (VARE, SystemIO, 0x72, 0x02)
Warning  3175 -                             ^ Static OperationRegion should be declared outside control method

dsdt.dsl   1074:         OperationRegion (VARE, SystemIO, 0x72, 0x02)
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\LM15)

dsdt.dsl   1087:         OperationRegion (VARE, SystemIO, 0x72, 0x02)
Warning  3175 -                             ^ Static OperationRegion should be declared outside control method

dsdt.dsl   1087:         OperationRegion (VARE, SystemIO, 0x72, 0x02)
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\LM16)

dsdt.dsl   1257:         OperationRegion (VARM, SystemIO, 0x80, 0x04)
Warning  3175 -                             ^ Static OperationRegion should be declared outside control method

dsdt.dsl   1257:         OperationRegion (VARM, SystemIO, 0x80, 0x04)
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\TPST)

dsdt.dsl   1405:             ElseIf (CondRefOf (\_OS, Local0))
Warning  3144 -        Method Local is set but never used ^  (Local0)

dsdt.dsl   1449:         Name (BUF0, Buffer (Local0){})
Remark   2173 -                  ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\SEQL)

dsdt.dsl   1451:         Name (BUF1, Buffer (Local0){})
Remark   2173 -                  ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\SEQL)

dsdt.dsl   1488:         \_SB.PCI0.SMB.PEWS = \_SB.PCI0.SMB.PEWS
Warning  3023 -  Duplicate value in list ^  (Source is the same as Target)

dsdt.dsl   1586:         \_SB.PCI0.SMB.PEWS = \_SB.PCI0.SMB.PEWS
Warning  3023 -  Duplicate value in list ^  (Source is the same as Target)

dsdt.dsl   1844:         Device (PCI0)
Warning  3073 -     Multiple types ^  (Device object requires either a _HID or _ADR, but not both)

dsdt.dsl   2192:                 CreateDWordField (RSRC, \_SB.PCI0._Y01._MIN, BT2S)  // _MIN: Minimum Base Address
Remark   2089 -                                        Object is not referenced ^  (Name [BT2S] is within a method [_CRS])

dsdt.dsl   2193:                 CreateDWordField (RSRC, \_SB.PCI0._Y01._MAX, BT2M)  // _MAX: Maximum Base Address
Remark   2089 -                                        Object is not referenced ^  (Name [BT2M] is within a method [_CRS])

dsdt.dsl   2194:                 CreateDWordField (RSRC, \_SB.PCI0._Y01._LEN, BT2L)  // _LEN: Length
Remark   2089 -                                        Object is not referenced ^  (Name [BT2L] is within a method [_CRS])

dsdt.dsl   2816:                     Method (WRDD, 0, Serialized)
Warning  3115 -                                ^ Not all control paths return a value (\_SB.PCI0.GPP5.PXSX.WRDD)

dsdt.dsl   2820:                             Return (Package (0x03)
Remark   2063 -                                                 ^ Initializer list shorter than declared package length

dsdt.dsl   2832:                     Method (WRDS, 0, Serialized)
Warning  3115 -                                ^ Not all control paths return a value (\_SB.PCI0.GPP5.PXSX.WRDS)

dsdt.dsl   2836:                             Return (Package (0x03)
Remark   2063 -                                                 ^ Initializer list shorter than declared package length

dsdt.dsl   2864:                 Method (_DSM, 4, Serialized)  // _DSM: Device-Specific Method
Warning  3115 -                            ^ Not all control paths return a value (\_SB.PCI0.GPP5._DSM)

dsdt.dsl   2864:                 Method (_DSM, 4, Serialized)  // _DSM: Device-Specific Method
Warning  3107 -                            ^ Reserved method must return a value (Integer/String/Buffer/Package/Reference required for _DSM)

dsdt.dsl   2866:                     If ((Arg0 == ToUUID ("079ff457-64a8-44be-bd8a-6955052b9b92") /* Unknown UUID */))
Remark   2184 -                                                           Unknown UUID string ^ 

dsdt.dsl   2872:                                 Switch (Arg1)
Warning  3124 -                                            ^ Switch expression is not a static Integer/Buffer/String data type, defaulting to Integer

dsdt.dsl   2895:                     ElseIf ((Arg0 == ToUUID ("f21202bf-8f78-4dc6-a5b3-1f738e285ade") /* Unknown UUID */))
Remark   2184 -                                                               Unknown UUID string ^ 

dsdt.dsl   4212:                     Local1 = PD64 /* \_SB_.PCI0.LPC0.PD64 */
Warning  3144 -                          ^ Method Local is set but never used (Local1)

dsdt.dsl   4950:                         CreateDWordField (MSRC, \_SB.PCI0.LPC0.MEM._Y07._LEN, ML01)  // _LEN: Length
Remark   2089 -                                                         Object is not referenced ^  (Name [ML01] is within a method [_CRS])

dsdt.dsl   5480:                         Local1 = 0x00
Warning  3144 -                              ^ Method Local is set but never used (Local1)

dsdt.dsl   5481:                         Local2 = 0x00
Warning  3144 -                              ^ Method Local is set but never used (Local2)

dsdt.dsl   5840:                     Method (BATW, 1, NotSerialized)
Remark   2146 -  Method Argument is never used ^  (Arg0)

dsdt.dsl   5903:                     Method (GBIF, 3, NotSerialized)
Remark   2146 -  Method Argument is never used ^  (Arg0)

dsdt.dsl   5903:                     Method (GBIF, 3, NotSerialized)
Remark   2120 -                                ^ Control Method should be made Serialized due to creation of named objects within (\_SB.PCI0.LPC0.EC0.GBIF)

dsdt.dsl   5947:                             Name (SERN, Buffer (0x06)
Remark   2173 -                                      ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.LPC0.EC0.GBIF)

dsdt.dsl   5981:                     Method (GBIX, 3, NotSerialized)
Remark   2146 -  Method Argument is never used ^  (Arg0)

dsdt.dsl   5981:                     Method (GBIX, 3, NotSerialized)
Remark   2120 -                                ^ Control Method should be made Serialized due to creation of named objects within (\_SB.PCI0.LPC0.EC0.GBIX)

dsdt.dsl   6027:                             Name (SERN, Buffer (0x06)
Remark   2173 -                                      ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.LPC0.EC0.GBIX)

dsdt.dsl   6061:                     Method (GBST, 4, NotSerialized)
Remark   2146 -  Method Argument is never used ^  (Arg0)

dsdt.dsl   6122:                                 Divide (Local1, 0x03E8, Local7, Local1)
Warning  3144 -                           Method Local is set but never used ^  (Local7)

dsdt.dsl   6731:                         Method (MHSC, 1, NotSerialized)
Remark   2146 -      Method Argument is never used ^  (Arg0)

dsdt.dsl   6775:                         Method (MHSE, 1, NotSerialized)
Remark   2146 -      Method Argument is never used ^  (Arg0)

dsdt.dsl   6784:                         Method (MLCG, 1, NotSerialized)
Remark   2146 -      Method Argument is never used ^  (Arg0)

dsdt.dsl   6808:                         Method (DSSG, 1, NotSerialized)
Remark   2146 -      Method Argument is never used ^  (Arg0)

dsdt.dsl   6819:                         Method (SBSG, 1, NotSerialized)
Remark   2146 -      Method Argument is never used ^  (Arg0)

dsdt.dsl   6829:                         Method (PBLG, 1, NotSerialized)
Remark   2146 -      Method Argument is never used ^  (Arg0)

dsdt.dsl   6853:                         Method (PMSG, 1, NotSerialized)
Remark   2146 -      Method Argument is never used ^  (Arg0)

dsdt.dsl   6865:                         Method (ISSG, 1, NotSerialized)
Remark   2146 -      Method Argument is never used ^  (Arg0)

dsdt.dsl   6884:                         Method (FFSG, 1, NotSerialized)
Remark   2146 -      Method Argument is never used ^  (Arg0)

dsdt.dsl   6889:                         Method (FFSS, 1, NotSerialized)
Remark   2146 -      Method Argument is never used ^  (Arg0)

dsdt.dsl   6936:                         Method (INSG, 1, NotSerialized)
Remark   2146 -      Method Argument is never used ^  (Arg0)

dsdt.dsl   6995:                         Method (MHGI, 1, NotSerialized)
Remark   2120 -                                    ^ Control Method should be made Serialized due to creation of named objects within (\_SB.PCI0.LPC0.EC0.HKEY.MHGI)

dsdt.dsl   6997:                             Name (RETB, Buffer (0x10){})
Remark   2173 -                                      ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.LPC0.EC0.HKEY.MHGI)

dsdt.dsl   7017:                                     CreateByteField (RETB, 0x01, MHGZ)
Remark   2089 -                                            Object is not referenced ^  (Name [MHGZ] is within a method [MHGI])

dsdt.dsl   7056:                                             Local1 = (RBEC (0x47) & 0x01)
Warning  3144 -               Method Local is set but never used ^  (Local1)

dsdt.dsl   7170:                         Method (SBIG, 1, NotSerialized)
Remark   2146 -      Method Argument is never used ^  (Arg0)

dsdt.dsl   7382:             Method (GSMS, 1, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl   7650:             Method (GHSL, 1, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl   7863:             Method (WGWK, 1, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl   8944:             Method (WMA1, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl   8944:             Method (WMA1, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg1)

dsdt.dsl   8968:             Method (WMA2, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl   8968:             Method (WMA2, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg1)

dsdt.dsl   8989:             Method (WMA3, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl   8989:             Method (WMA3, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg1)

dsdt.dsl   9010:             Method (WMA4, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl   9010:             Method (WMA4, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg1)

dsdt.dsl   9031:             Method (WQA5, 1, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl   9034:                 Local0 = WMIS (0x05, 0x00)
Warning  3144 -                      ^ Method Local is set but never used (Local0)

dsdt.dsl   9045:             Method (WMA6, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl   9045:             Method (WMA6, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg1)

dsdt.dsl   9073:             Method (WMA7, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl   9073:             Method (WMA7, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg1)

dsdt.dsl   9127:             Method (WMC0, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl   9127:             Method (WMC0, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg1)

dsdt.dsl   9150:                             Local5 = (SizeOf (Arg2) - Local2)
Warning  3144 -                                  ^ Method Local is set but never used (Local5)

dsdt.dsl   9278:             Method (SCMP, 3, NotSerialized)
Remark   2120 -                        ^ Control Method should be made Serialized due to creation of named objects within (\_SB.WMI1.SCMP)

dsdt.dsl  10107:             Method (WQA7, 1, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl  10123:             Method (WMA8, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl  10123:             Method (WMA8, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg1)

dsdt.dsl  10280:             Method (WMAA, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl  10280:             Method (WMAA, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg1)

dsdt.dsl  10491:             Method (WMAB, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl  10491:             Method (WMAB, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg1)

dsdt.dsl  10506:             Method (WMAC, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl  10699:             Method (WMAD, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl  10699:             Method (WMAD, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg1)

dsdt.dsl  10968:             Method (WQGN, 1, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl  10976:             Method (WQGM, 1, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl  10984:             Method (WMSC, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl  10984:             Method (WMSC, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg1)

dsdt.dsl  11024:             Method (WMGC, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl  11024:             Method (WMGC, 3, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg1)

dsdt.dsl  11064:             Method (WQEC, 1, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl  11077:             Method (WQNS, 1, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl  11381:             Method (MHPF, 1, NotSerialized)
Remark   2120 -                        ^ Control Method should be made Serialized due to creation of named objects within (\_SB.PCI0.LPC0.EC0.HKEY.MHPF)

dsdt.dsl  11383:                 Name (RETB, Buffer (0x25){})
Remark   2173 -                          ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.LPC0.EC0.HKEY.MHPF)

dsdt.dsl  11402:             Method (MHIF, 1, NotSerialized)
Remark   2120 -                        ^ Control Method should be made Serialized due to creation of named objects within (\_SB.PCI0.LPC0.EC0.HKEY.MHIF)

dsdt.dsl  11404:                 Name (RETB, Buffer (0x0A){})
Remark   2173 -                          ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.LPC0.EC0.HKEY.MHIF)

dsdt.dsl  11420:             Method (PSSG, 1, NotSerialized)
Remark   2146 -                        ^ Method Argument is never used (Arg0)

dsdt.dsl  11929:             OperationRegion (ADCR, SystemMemory, Local0, 0x02)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.SRAD)

dsdt.dsl  11954:             OperationRegion (ADCR, SystemMemory, Local0, 0x02)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.DSAD)

dsdt.dsl  11996:             Local3 = (0x01 << Arg0)
Warning  3144 -                  ^ Method Local is set but never used (Local3)

dsdt.dsl  11999:             OperationRegion (ADCR, SystemMemory, Local0, 0x02)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.HSAD)

dsdt.dsl  12090:             Method (_CRS, 0, NotSerialized)  // _CRS: Current Resource Settings
Remark   2120 -                        ^ Control Method should be made Serialized due to creation of named objects within (\_SB.HFP1._CRS)

dsdt.dsl  12092:                 Name (RBUF, ResourceTemplate ()
Remark   2173 -                          ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.HFP1._CRS)

dsdt.dsl  12108:             Method (_CRS, 0, NotSerialized)  // _CRS: Current Resource Settings
Remark   2120 -                        ^ Control Method should be made Serialized due to creation of named objects within (\_SB.GPIO._CRS)

dsdt.dsl  12110:                 Name (RBUF, ResourceTemplate ()
Remark   2173 -                          ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.GPIO._CRS)

dsdt.dsl  12224:             Name (XX11, Buffer (0x07){})
Remark   2173 -                      ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.LPC0.EC0.HKEY.DYTC)

dsdt.dsl  12225:             Name (TSCB, 0x0F)
Remark   2089 -                      ^ Object is not referenced (Name [TSCB] is within a method [DYTC])

dsdt.dsl  12225:             Name (TSCB, 0x0F)
Remark   2173 -                      ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.LPC0.EC0.HKEY.DYTC)

dsdt.dsl  12226:             Name (TSCC, 0x0F)
Remark   2089 -                      ^ Object is not referenced (Name [TSCC] is within a method [DYTC])

dsdt.dsl  12226:             Name (TSCC, 0x0F)
Remark   2173 -                      ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.LPC0.EC0.HKEY.DYTC)

dsdt.dsl  12245:                     Switch (Local2)
Warning  3124 -                                  ^ Switch expression is not a static Integer/Buffer/String data type, defaulting to Integer

dsdt.dsl  12402:                         Switch (Local7)
Warning  3124 -                                      ^ Switch expression is not a static Integer/Buffer/String data type, defaulting to Integer

ASL Input:     dsdt.dsl -  472402 bytes   4761 keywords  12846 source lines
AML Output:    dsdt.aml -   53997 bytes   3659 opcodes    1102 named objects

Compilation successful. 0 Errors, 22 Warnings, 104 Remarks, 1231 Optimizations, 1 Constants Folded
`

**Comment by atisDu** [comment]
Nevermind, grub was behaving weirdly for me, it is working now. Thanks for your work and sorry for wasting your time!

**Comment by ghost** [comment]
Aha good to know . It's fine , if you come across anything just report here . Lenovo dosent seem to care about this anyway . We should do what we can .Also almost all of the work was done by @masksshow  . I just changed some directories and maybe 1 or two line in the scripts . 
Also the script is mostly intended for systems with grub . So keep that in mind. Like pop os uses systemd-boot . So you will have to install and configure grub first.
Anyways its fine as long as its working 😃.
